 
# arithmetic/logical
ADD = 0
SUB = 1
LOAD = 2
STORE = 3
COMPARE = 4
JUMP = 5
# io
OUTPUT = 6
INPUT = 7
HALT = 8

# comparison
MIN = ADD
MAX = HALT

# purpose of instruction
INSTRUCTION = 255
DATA = INSTRUCTION + 1

TYPE_FLOAT = DATA + 1
TYPE_INTEGER = TYPE_FLOAT + 1
TYPE_STRING = TYPE_INTEGER + 1

# instruction presets
JUMP_ALWAYS = 300
JUMP_ZERO = JUMP_ALWAYS + 1
JUMP_POSITIVE = JUMP_ALWAYS + 2

MIN_PRESET = JUMP_ALWAYS
MAX_PRESET = JUMP_POSITIVE
